version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: indian-numismatics
    path: dictionaries/indian-numismatics.txt
  - name: chinese-numismatics
    path: dictionaries/chinese-numismatics.txt
  - name: islamic-numismatics
    path: dictionaries/islamic-numismatics.txt
dictionaries:
  - en_US
  - en_GB
  # You may need `npm install --global @cspell/dict-ar` for the Arabic dictionary
  - ar
  - indian-numismatics
  - chinese-numismatics
  - islamic-numismatics
words:
  - Aluminium
  - analyse
  - analysed
  - authorised
  - Bacchante
  - bookface
  - Claudian
  - civilisation
  - dependants
  - Fitzwilliam
  - maximise
  - lxxxii
  - mell
  - mintages
  - modernisation
  - neighbourhood
  - paise
  - realise
  - reattributed
  - pell
  - Seaby's
  - Sotheby's
  - summarise
  - synchronised
  - unauthorised
  - undeciphered
  - unfavourable
  - unilinear
  - utilise
  - utilising
  - patronised
  - fulfilment
  - tantalisingly
  - counterstruck
  - uncountermarked
  - monetise
  - demonetising
  - minimised
  - characterisation
  - systematise
  - formalise
  - contextualise
  - polarising
  - italicised
  - Islamise
  - Arabise
  - habitational
  - patinating
  - patronyms
  - inspissated
  - halfweight
  - mintplace
  - defence
  - favourites
  - crieth
  - headwear
  - sowings
  - somniferum
  - Papaver
  - Papaveraceae
  - Cruciferae
  - Brassicae
  - unresearched
  - religio
  - angespielt
  - Argumente
  - aufrechtzuerhalten
  - ausgeschlossen
  - bereits
  - Beweisende
  - bewiesen
  - Bezug
  - Bild
  - Bildsprache
  - Daß
  - dagegen
  - daher
  - Deutung
  - dürfte
  - Ehrbezeugung
  - eindeutig
  - eingeflossen
  - Elemente
  - etwas
  - extrem
  - Fabrizio
  - Gesten
  - gewichtige
  - gibt
  - griechischen
  - Kollegen
  - kommt
  - laut
  - Mauerkrone
  - meinem
  - Sinisi
  - schwer
  - sein
  - setzt
  - soll
  - Übergebende
  - übergibt
  - unwahrscheinlich
  - Vergleichsbeispielen
  - voraus
  - vorliegenden
  - wodurch
  - würde
  - geprägt
  - Münze
  - Österreichische
  - vollführt
  - Akademie
  - hier
  - iranische
  - iranischen
ignoreWords: []
import: []
